# Generated by Django 4.1.6 on 2023-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('published_company', models.CharField(max_length=255)),
                ('link_published', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_type', models.IntegerField(choices=[(1, 'Conference'), (2, 'Symposium'), (3, 'Workshop'), (4, 'Seminar'), (5, 'Colloquium'), (6, 'Roundtable')], default=1)),
                ('conference_name', models.CharField(max_length=255)),
                ('conference_start_date', models.DateField()),
                ('conference_end_date', models.DateField()),
                ('conference_location', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('participant_name', models.CharField(max_length=255, null=True)),
                ('paper_info', models.TextField(null=True)),
                ('link_published', models.URLField(blank=True, null=True)),
                ('link_of_dissemination', models.URLField(blank=True, null=True)),
                ('nationality_or_international', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('issn', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('published_place', models.CharField(max_length=255)),
                ('impactor_factor', models.PositiveSmallIntegerField(choices=[(1, 'Web of Science'), (2, 'Scopus'), (3, 'Other')])),
                ('link_published', models.URLField(blank=True, null=True)),
                ('doi_journal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InternalProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('project_duration', models.DurationField()),
                ('meeting_date', models.DateField()),
                ('link_to_official_page', models.URLField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_of_dissemination', models.URLField(blank=True, null=True)),
                ('project_coordinator', models.CharField(max_length=255)),
                ('events', models.ManyToManyField(blank=True, related_name='%(class)s', to='epoka_projects.events')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('project_duration', models.DurationField()),
                ('meeting_date', models.DateField()),
                ('link_to_official_page', models.URLField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_of_dissemination', models.URLField(blank=True, null=True)),
                ('project_partner', models.CharField(max_length=255)),
                ('events', models.ManyToManyField(blank=True, related_name='%(class)s', to='epoka_projects.events')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
