# Generated by Django 4.1.6 on 2023-02-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epoka_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprojects',
            name='project_duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internalprojects',
            name='project_duration',
            field=models.CharField(max_length=255),
        ),
    ]
